import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Chunk text into smaller pieces
function chunkText(text: string, chunkSize = 500, overlap = 50): string[] {
  const chunks: string[] = [];
  const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0);
  
  let currentChunk = "";
  
  for (const sentence of sentences) {
    const trimmedSentence = sentence.trim();
    if (currentChunk.length + trimmedSentence.length > chunkSize && currentChunk.length > 0) {
      chunks.push(currentChunk.trim());
      // Keep overlap from the end of current chunk
      const words = currentChunk.split(" ");
      const overlapWords = words.slice(-Math.ceil(overlap / 10));
      currentChunk = overlapWords.join(" ") + " " + trimmedSentence;
    } else {
      currentChunk += (currentChunk ? ". " : "") + trimmedSentence;
    }
  }
  
  if (currentChunk.trim()) {
    chunks.push(currentChunk.trim());
  }
  
  return chunks.length > 0 ? chunks : [text];
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { documentId, content, title, sourceType, sourceUrl } = await req.json();

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    const supabase = createClient(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!);

    console.log("Processing document:", title);

    // Create or update document
    let docId = documentId;
    if (!docId) {
      const { data: doc, error: docError } = await supabase
        .from("rag_documents")
        .insert({
          title,
          source_type: sourceType || "text",
          source_url: sourceUrl,
          content,
        })
        .select()
        .single();

      if (docError) {
        console.error("Error creating document:", docError);
        throw docError;
      }
      docId = doc.id;
      console.log("Created document:", docId);
    }

    // Chunk the content
    const chunks = chunkText(content);
    console.log(`Created ${chunks.length} chunks`);

    // Delete existing chunks for this document
    await supabase.from("rag_chunks").delete().eq("document_id", docId);

    // Insert chunks (search_vector will be auto-generated by trigger)
    const chunksToInsert = chunks.map((chunk, index) => ({
      document_id: docId,
      content: chunk,
      chunk_index: index,
    }));

    const { error: chunkError } = await supabase
      .from("rag_chunks")
      .insert(chunksToInsert);

    if (chunkError) {
      console.error("Error inserting chunks:", chunkError);
      throw chunkError;
    }

    console.log(`Inserted ${chunks.length} chunks with full-text search enabled`);

    return new Response(
      JSON.stringify({
        success: true,
        documentId: docId,
        chunksCreated: chunks.length,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error in rag-embed function:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
